- name: copy a repository file for mongodb
  copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb-org.repo

- name: install mongodb packages
  tags: packages
  package: 
    name: "{{ item }}"
    state: latest
  with_items:
    - mongodb-org

- name: start mongodb
  service: name=mongod state=restarted enabled=yes
  when: not ansible_check_mode
