- name: install packages
  tags: packages
  yum: 
    name: ['openstack-neutron', 'openstack-neutron-linuxbridge', 'openstack-neutron-lbaas', 'ebtables', 'ipset', 'haproxy']
    state: latest

#- name: install configurations
#  tags: config
- block:
  - template: 
      src: linuxbridge_agent.ini.j2 
      dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini
  - copy: 
      src: l3_agent.ini
      dest: /etc/neutron/l3_agent.ini
  - copy: 
      src: dhcp_agent.ini 
      dest: /etc/neutron/dhcp_agent.ini
  - template: 
      src: neutron_lbaas.conf.j2 
      dest: /etc/neutron/neutron_lbaas.conf
  - template: 
      src: metadata_agent.ini.j2 
      dest: /etc/neutron/metadata_agent.ini
#  - file: 
#      src: /etc/neutron/plugins/ml2/ml2_conf.ini 
#      dest: /etc/neutron/plugin.ini 
#      state: link
    when: not ansible_check_mode

- copy: 
    src: dnsmasq-neutron.conf 
    dest: /etc/neutron/dnsmasq-neutron.conf


- name: install configurations
  tags: config
  template: 
    src: "{{ item }}.j2" 
    dest: "/etc/neutron/{{ item }}"
  with_items:
    - neutron.conf
    - lbaas_agent.ini

- name: install configurations
  tags: config
  template: 
    src: linuxbridge_agent.ini.j2 
    dest: /etc/neutron/plugins/ml2/linuxbridge_agent.ini

- name: start services
  tags: service
  systemd: 
    name: "{{ item }}" 
    state: started 
    enabled: yes
  when: not ansible_check_mode
  with_items:
    - openstack-nova-compute
    - neutron-linuxbridge-agent
    - neutron-lbaasv2-agent
