- name: install packages
  tags: packages
  dnf: 
    name: "{{ item }}"
    state: latest
  loop:
    - openstack-nova-compute
    - sysfsutils

- name: install nova configuration
  tags: config
  template: 
    src: "{{ item }}.j2" 
    dest: "/etc/nova/{{ item }}"
  with_items:
    - nova.conf

- name: start services
  tags: service
  systemd: 
    name: "{{ item }}"
    state: restarted 
    enabled: yes
  #when: not ansible_check_mode
  with_items:
    - libvirtd
    - openstack-nova-compute
