- name: install packages
  tags: packages
  yum: 
    name: ['openstack-nova-compute', 'sysfsutils']
    state: latest

- name: install nova configuration
  tags: config
  template: 
    src: "{{ item }}.j2" 
    dest: "/etc/nova/{{ item }}"
  with_items:
    - nova.conf

- name: start services
  tags: service
  systemd: 
    name: "{{ item }}"
    state: restarted 
    enabled: yes
  when: not ansible_check_mode
  with_items:
    - libvirtd
    - openstack-nova-compute
