# memcached
- name: install memcached packages
  tags: packages
  package: name=memcached state=latest

- name: configure memcached
  template: src=memcached.j2 dest=/etc/sysconfig/memcached

- name: start memcached
  tags: service
  service: name=memcached state=restarted enabled=yes
  when: not ansible_check_mode